# Generated by Django 4.0.2 on 2022-02-18 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OpenDataApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gallery',
            old_name='image',
            new_name='general',
        ),
    ]
